# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: 'Install Postgres SQL server'
    before: |
      # Build docker image
      docker build -t app-postgres-image .
    init: |
      # Start PostgreSQL container using the custom docker image
      docker run --name pern-todo-postgres-container -d -p 5432:5432 app-postgres-image

  - name: 'Initialize backend server'
    init: cd server && npm i
    command: echo 'Run `npm run dev` for development mode -OR- `npm start` for production mode'

  - name: 'Initialize frontend server'
    init: cd client && npm i
    command: echo "Need proper script to run frontend repository"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend server
    description: Client application
    port: 3000
    onOpen: open-preview

  - name: Backend server
    description: Server application
    port: 5000
    onOpen: open-preview

  - name: PostgreSQL Database
    description: PERN-TODO App Database
    port: 5432
    onOpen: ignore # Not need to open a preview for PostgreSQL
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
